site_name: copick
repo_url: "https://github.com/uermel/copick"
repo_name: "uermel/copick"
copyright: "2024, Utz Heinrich Ermel, Kyle I. S. Harrington"
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  logo: assets/logo.png
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Data Model: datamodel.md
  - Examples:
    - Overview: "examples/overview.md"
    - Setup:
      - Local Project: "examples/setup/local.md"
      - Shared Project: "examples/setup/shared.md"
      - AWS S3 Project: "examples/setup/aws_s3.md"
      - SSH Project: "examples/setup/ssh.md"
      - CZ cryoET Data Portal: "examples/setup/data_portal.md"
    - Tutorials:
      - CZ cryoET Data Portal: "examples/tutorials/data_portal.md"
      - Copick and HPC: "examples/tutorials/hpc.md"
      - ChimeraX-Copick: "examples/tutorials/chimerax.md"
      - Copick and Album: "examples/tutorials/album.md"
      - Detecting Sample Boundaries: "examples/tutorials/sample_boundaries.md"
      - Copick and membrain-seg: "examples/tutorials/membrain.md"
    - Snippets: "examples/snippets.md"

  - Tools: tools.md
  #- Tools: tools.md
  - API Reference:
    - API Overview: "api_reference/api.md"
    - Base Classes:
      - Data Entity Models:
        - CopickRoot: "api_reference/base_classes/data_entity_models/CopickRoot.md"
        - CopickObject: "api_reference/base_classes/data_entity_models/CopickObject.md"
        - CopickRun: "api_reference/base_classes/data_entity_models/CopickRun.md"
        - CopickVoxelSpacing: "api_reference/base_classes/data_entity_models/CopickVoxelSpacing.md"
        - CopickTomogram: "api_reference/base_classes/data_entity_models/CopickTomogram.md"
        - CopickFeatures: "api_reference/base_classes/data_entity_models/CopickFeatures.md"
        - CopickPicks: "api_reference/base_classes/data_entity_models/CopickPicks.md"
        - CopickMesh: "api_reference/base_classes/data_entity_models/CopickMesh.md"
        - CopickSegmentation: "api_reference/base_classes/data_entity_models/CopickSegmentation.md"
      - Metadata Models:
        - CopickConfig: "api_reference/base_classes/metadata_models/CopickConfig.md"
        - PickableObject: "api_reference/base_classes/metadata_models/PickableObject.md"
        - CopickPicksFile: "api_reference/base_classes/metadata_models/CopickPicksFile.md"
        - CopickRunMeta: "api_reference/base_classes/metadata_models/CopickRunMeta.md"
        - CopickVoxelSpacingMeta: "api_reference/base_classes/metadata_models/CopickVoxelSpacingMeta.md"
        - CopickTomogramMeta: "api_reference/base_classes/metadata_models/CopickTomogramMeta.md"
        - CopickFeaturesMeta: "api_reference/base_classes/metadata_models/CopickFeaturesMeta.md"
        - CopickMeshMeta: "api_reference/base_classes/metadata_models/CopickMeshMeta.md"
        - CopickSegmentationMeta: "api_reference/base_classes/metadata_models/CopickSegmentationMeta.md"

    - Implementations:
      - Overlay: "api_reference/implementations/Overlay.md"
      - File System: "api_reference/implementations/Filesystem.md"
      - Data Portal: "api_reference/implementations/Dataportal.md"

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            # General
            show_source: false
            preload_modules: [pydantic]
            # Headings
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_root_full_path: true
            show_root_heading: true
            # Members
            group_by_category: true
            show_labels: false
            inherited_members: false
            members_order: source
            # Docstrings
            docstring_section_style: list
            merge_init_into_class: false
            docstring_style: google
            # Signatures
            show_signature_annotations: true
            signature_crossrefs: false


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      base_path: [ docs/snippets, docs/templates, "." ]
