"""Generate per-command CLI reference pages from the assembled copick CLI.

This walks the fully-assembled ``copick`` Click group (core commands plus every
plugin command contributed by copick-utils, copick-torch, copick-mcp, ...) and
renders one Markdown page per command into ``docs/cli/``. Command ``--help`` /
docstrings are the single source of truth: descriptions, ``Arguments:``,
``URI Format:``, ``Examples:``, ``See Also:`` and ``Notes:`` sections come from
the docstring, while the option/argument tables are built from the live Click
parameter objects so they can never drift from the actual CLI.

A generated page can carry hand-written editorial content (figures, extended
prose, tips): create ``docs/cli_editorial/<.../command>.md`` and regenerate, and
the page gains a ``pymdownx.snippets`` include of it at the bottom. Editorial
partials are authored by hand and never written or overwritten by the generator,
so they survive regeneration; pages without one simply omit the include.

The generator also rewrites *only* the ``CLI Reference`` element of the
``nav`` array in ``zensical.toml`` (a targeted text splice that preserves the
rest of the file byte-for-byte), grouped by the same ``COMMAND_CATEGORIES`` used
for ``copick --help``.

It also emits a visual **Processing Tools gallery** (``docs/processing_tools.md``)
and a carousel teaser snippet (``docs/snippets/processing_carousel.snippet``)
from the same introspection — one card per convert/process/logical command, with
a thumbnail resolved from ``docs/assets/tools/<group>/<command>.<ext>`` (falling
back to a shared placeholder until a real render is dropped in).

Run ``make_cli_docs`` to (re)generate, or ``make_cli_docs --check`` to verify
the committed docs are up to date (used in CI / pre-commit).
"""

import inspect
import os
import re
import textwrap
from typing import Dict, List, Optional, Tuple

import click

from copick.cli.cli import COMMAND_CATEGORIES, cli
from copick.util.log import get_logger

logger = get_logger(__name__)

AUTOGEN_HEADER = (
    "<!-- AUTOGENERATED by `make_cli_docs` (copick.cli.make_cli_docs). Do not edit by hand.\n"
    "     Editorial additions go in the matching docs/cli_editorial/ partial. -->\n"
)

# Recognised docstring section headers (a closed vocabulary, matched at column 0
# after dedent). "Example" and "Examples" are both accepted.
_SECTION_RE = re.compile(r"^(Arguments|URI Format|Examples?|See Also|Notes):\s*$")


# --------------------------------------------------------------------------- #
# Click introspection helpers
# --------------------------------------------------------------------------- #
def _is_group(obj: click.Command) -> bool:
    return isinstance(obj, click.Group)


def _group_of(param: click.Parameter):
    """Return the ``click_option_group`` OptionGroup a param belongs to, or None."""
    for key, value in vars(param).items():
        if key.endswith("__group"):
            return value
    return None


def _is_group_title(param: click.Parameter) -> bool:
    return type(param).__name__ == "_GroupTitleFakeOption"


def _arg_metavar(cmd: click.Command, arg: click.Argument, parent_ctx: click.Context) -> str:
    """Best-effort metavar for a positional argument (e.g. ``PATH`` or ``{a|b}``)."""
    if arg.metavar:
        return arg.metavar
    try:
        child = click.Context(cmd, info_name=cmd.name, parent=parent_ctx)
        return arg.make_metavar(child)
    except Exception:
        try:
            return arg.make_metavar()
        except Exception:
            return arg.name.upper()


def _type_label(param: click.Parameter) -> str:
    """Human-readable type for an option, e.g. ``choice (x | y | z)`` or ``integer``."""
    if getattr(param, "is_flag", False):
        label = "boolean flag"
    else:
        tname = getattr(param.type, "name", "text")
        choices = getattr(param.type, "choices", None)
        label = "choice (" + " \\| ".join(str(c) for c in choices) + ")" if choices else tname
    if getattr(param, "multiple", False):
        label += " · multiple"
    return label


def _is_unset(value) -> bool:
    # Click 8.2 uses a ``Sentinel.UNSET`` enum member for "no default".
    return value is None or type(value).__name__ == "Sentinel"


def _default_label(param: click.Parameter) -> str:
    if getattr(param, "required", False):
        return "**required**"
    default = getattr(param, "default", None)
    if _is_unset(default):
        return "—"
    if isinstance(default, str):
        return f'`"{default}"`' if default == "" else f"`{default}`"
    if isinstance(default, (list, tuple)) and len(default) == 0:
        return "—"
    return f"`{default}`"


def _opt_names(param: click.Parameter) -> str:
    primary = ", ".join(param.opts)
    if getattr(param, "secondary_opts", None):
        primary += " / " + ", ".join(param.secondary_opts)
    return f"`{primary}`"


def _cell(text: Optional[str]) -> str:
    """Sanitise a help string for a Markdown table cell."""
    if not text:
        return ""
    return " ".join(text.split()).replace("|", "\\|")


# --------------------------------------------------------------------------- #
# Docstring parsing
# --------------------------------------------------------------------------- #
def _parse_doc(doc: Optional[str], synopsis: str) -> Tuple[str, Dict[str, str]]:
    """Split a command docstring into (description prose, {section: body}).

    Tolerates both normalised (real ``\\x08`` no-wrap markers) and un-normalised
    (literal ``\\b``) docstrings.
    """
    if not doc:
        return "", {}

    # Drop the Click no-wrap marker lines entirely (real ``\x08`` after normalisation,
    # or a literal ``\b`` left over from un-normalised docstrings), so they leave no
    # stray blank lines. Genuine blank lines between blocks are preserved.
    lines = []
    for raw in doc.split("\n"):
        unmarked = raw.replace("\x08", "")
        if raw != unmarked and not unmarked.strip():
            continue
        if unmarked.strip() == "\\b":
            continue
        lines.append(unmarked)

    # Drop a leading summary line that merely duplicates the synopsis.
    while lines and not lines[0].strip():
        lines.pop(0)
    if lines and lines[0].strip().rstrip(".").lower() == synopsis.strip().rstrip(".").lower():
        lines.pop(0)

    pre: List[str] = []
    sections: Dict[str, List[str]] = {}
    current: Optional[str] = None
    for line in lines:
        match = _SECTION_RE.match(line.strip()) if line == line.strip() else None
        if match:
            label = match.group(1)
            label = "Examples" if label.startswith("Example") else label
            current = label
            sections.setdefault(current, [])
            continue
        if current is None:
            pre.append(line)
        else:
            sections[current].append(line)

    description = "\n".join(pre).strip()
    cleaned = {k: textwrap.dedent("\n".join(v)).strip("\n") for k, v in sections.items()}
    return description, cleaned


def _render_section(label: str, body: str, command_path: List[str]) -> str:
    if label == "Examples":
        return f"## Examples\n\n```bash\n{body}\n```\n"
    if label == "URI Format":
        return f"## URI Format\n\n```text\n{body}\n```\n"
    if label == "Arguments":
        rows = _kv_rows(body)
        if rows:
            out = ["## Arguments\n", "| Argument | Description |", "|----------|-------------|"]
            out += [f"| `{name}` | {_cell(desc)} |" for name, desc in rows]
            return "\n".join(out) + "\n"
        return f"## Arguments\n\n{body}\n"
    if label == "See Also":
        rows = _kv_rows(body)
        if rows:
            out = ["## See also\n"]
            out += [
                f"- {_link_command(name, command_path)} — {desc}" if desc else f"- {_link_command(name, command_path)}"
                for name, desc in rows
            ]
            return "\n".join(out) + "\n"
        return f"## See also\n\n{body}\n"
    if label == "Notes":
        return f"## Notes\n\n{body}\n"
    return f"## {label}\n\n{body}\n"


def _kv_rows(body: str) -> List[Tuple[str, str]]:
    """Parse ``NAME: description`` lines (folding hanging-indent continuations)."""
    rows: List[Tuple[str, str]] = []
    for raw in body.split("\n"):
        if not raw.strip():
            continue
        if ":" in raw and not raw.startswith((" ", "\t")):
            name, _, desc = raw.partition(":")
            rows.append((name.strip(), desc.strip()))
        elif rows:
            prev_name, prev_desc = rows[-1]
            rows[-1] = (prev_name, (prev_desc + " " + raw.strip()).strip())
    return rows


def _link_command(spec: str, from_path: List[str]) -> str:
    """Turn a ``See Also`` command spec into a relative link if it resolves."""
    parts = spec.strip().split()
    if parts and parts[0] == "copick":
        parts = parts[1:]
    target = _page_path_for(parts)
    if target is None:
        return f"`{spec.strip()}`"
    from_page = _page_path_for(from_path)
    rel = os.path.relpath(target, os.path.dirname(from_page))
    return f"[`copick {' '.join(parts)}`]({rel})"


# --------------------------------------------------------------------------- #
# Page-path / tree helpers
# --------------------------------------------------------------------------- #
_LEAF_PATHS: Dict[Tuple[str, ...], bool] = {}  # full path -> is_group


def _page_path_for(path: List[str]) -> Optional[str]:
    key = tuple(path)
    if key not in _LEAF_PATHS:
        return None
    if _LEAF_PATHS[key]:  # group
        return "docs/cli/" + "/".join(path) + "/index.md"
    return "docs/cli/" + "/".join(path) + ".md" if path else "docs/cli/index.md"


def _editorial_path_for(path: List[str], is_group: bool) -> str:
    """Repo-root-relative path of the hand-edited editorial partial for a command.

    Lives under ``docs/cli_editorial/`` (resolved by the ``.`` snippets base_path).
    """
    if not path:
        return "docs/cli_editorial/index.md"
    if is_group:
        return "docs/cli_editorial/" + "/".join(path) + "/index.md"
    return "docs/cli_editorial/" + "/".join(path) + ".md"


def _editorial_include(path: List[str], is_group: bool) -> str:
    """A snippets include line for the editorial partial, but only if it exists.

    Partials are never seeded empty: a command's page picks one up as soon as an
    author creates ``docs/cli_editorial/<.../command>.md`` and regenerates.
    """
    rel = _editorial_path_for(path, is_group)
    if os.path.exists(rel):
        return f'--8<-- "{rel}"\n'
    return ""


def _index_tree(ctx: click.Context) -> None:
    """Pre-compute the path->is_group map (needed for cross-page See-Also links)."""
    _LEAF_PATHS.clear()

    def walk(grp: click.Group, path: List[str]) -> None:
        for name in grp.list_commands(ctx):
            cmd = grp.get_command(ctx, name)
            if cmd is None or cmd.hidden:
                continue
            full = path + [name]
            _LEAF_PATHS[tuple(full)] = _is_group(cmd)
            if _is_group(cmd):
                walk(cmd, full)

    walk(cli, [])


# --------------------------------------------------------------------------- #
# Page rendering
# --------------------------------------------------------------------------- #
def _usage_line(cmd: click.Command, path: List[str], ctx: click.Context) -> str:
    parts = ["copick", *path, cmd.options_metavar or "[OPTIONS]"]
    if _is_group(cmd):
        parts.append("COMMAND [ARGS]...")
    else:
        for param in cmd.params:
            if isinstance(param, click.Argument):
                metavar = _arg_metavar(cmd, param, ctx)
                parts.append(metavar if param.required else f"[{metavar}]")
    return " ".join(p for p in parts if p)


def _option_tables(cmd: click.Command) -> str:
    """Render option tables, one per click_option_group section."""
    sections: "Dict[str, List[click.Parameter]]" = {}
    blurbs: Dict[str, str] = {}
    order: List[str] = []

    for param in cmd.params:
        if isinstance(param, click.Argument) or getattr(param, "hidden", False):
            continue
        group = _group_of(param)
        section = group.name.strip() if group is not None else "Options"
        if _is_group_title(param):
            blurbs[section] = param.help or ""
            continue
        if section not in sections:
            sections[section] = []
            order.append(section)
        sections[section].append(param)

    # "Options" (ungrouped) always renders first.
    if "Options" in order:
        order.remove("Options")
        order.insert(0, "Options")

    if not any(sections.values()):
        return ""

    out = ["## Options\n"]
    for section in order:
        params = sections.get(section, [])
        if not params:
            continue
        if section != "Options":
            out.append(f"### {section}\n")
        if blurbs.get(section):
            out.append(f"*{blurbs[section]}*\n")
        out.append("| Option | Type | Default | Description |")
        out.append("|--------|------|---------|-------------|")
        for param in params:
            out.append(
                f"| {_opt_names(param)} | {_type_label(param)} | {_default_label(param)} | {_cell(param.help)} |",
            )
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _render_leaf(cmd: click.Command, path: List[str], ctx: click.Context) -> str:
    synopsis = cmd.short_help or cmd.get_short_help_str() or "No description available."
    description, sections = _parse_doc(inspect.getdoc(cmd.callback) if cmd.callback else None, synopsis)

    blocks = [AUTOGEN_HEADER, f"# copick {' '.join(path)}\n", f"*{synopsis}*\n"]

    if getattr(cmd, "deprecated", False):
        msg = cmd.deprecated if isinstance(cmd.deprecated, str) else "This command is deprecated."
        blocks.append(f'!!! warning "Deprecated"\n    {msg}\n')

    blocks.append(f"## Usage\n\n```bash\n{_usage_line(cmd, path, ctx)}\n```\n")

    if description:
        blocks.append(f"## Description\n\n{description}\n")

    if "Arguments" in sections:
        blocks.append(_render_section("Arguments", sections["Arguments"], path))
    if "URI Format" in sections:
        blocks.append(_render_section("URI Format", sections["URI Format"], path))

    options = _option_tables(cmd)
    if options:
        blocks.append(options)

    for label in ("Examples", "See Also", "Notes"):
        if label in sections:
            blocks.append(_render_section(label, sections[label], path))

    blocks.append(_editorial_include(path, is_group=False))
    return "\n".join(b for b in blocks if b).rstrip() + "\n"


def _render_group(grp: click.Group, path: List[str], ctx: click.Context) -> str:
    title = "copick " + " ".join(path) if path else "copick CLI"
    synopsis = grp.short_help or grp.get_short_help_str() or ""
    description, sections = _parse_doc(inspect.getdoc(grp.callback) if grp.callback else None, synopsis)

    blocks = [AUTOGEN_HEADER, f"# {title}\n"]
    if synopsis:
        blocks.append(f"*{synopsis}*\n")
    blocks.append(f"## Usage\n\n```bash\n{_usage_line(grp, path, ctx)}\n```\n")
    if description:
        blocks.append(f"## Description\n\n{description}\n")

    rows = ["## Commands\n", "| Command | Description |", "|---------|-------------|"]
    for name in grp.list_commands(ctx):
        cmd = grp.get_command(ctx, name)
        if cmd is None or cmd.hidden:
            continue
        link = f"{name}/index.md" if _is_group(cmd) else f"{name}.md"
        desc = cmd.short_help or cmd.get_short_help_str() or ""
        rows.append(f"| [`{name}`]({link}) | {_cell(desc)} |")
    blocks.append("\n".join(rows) + "\n")

    blocks.append(_editorial_include(path, is_group=True))
    return "\n".join(b for b in blocks if b).rstrip() + "\n"


def _render_index(ctx: click.Context) -> str:
    """The CLI reference landing page: a category-grouped command index."""
    blocks = [AUTOGEN_HEADER, "# CLI Reference\n", "*The complete `copick` command-line interface.*\n"]

    top = {name: cli.get_command(ctx, name) for name in cli.list_commands(ctx)}
    top = {k: v for k, v in top.items() if v is not None and not v.hidden}
    seen = set()
    for category, names in COMMAND_CATEGORIES.items():
        present = [n for n in sorted(names) if n in top]
        if not present:
            continue
        seen.update(present)
        rows = [f"## {category}\n", "| Command | Description |", "|---------|-------------|"]
        for name in present:
            cmd = top[name]
            link = f"{name}/index.md" if _is_group(cmd) else f"{name}.md"
            desc = cmd.short_help or cmd.get_short_help_str() or ""
            rows.append(f"| [`{name}`]({link}) | {_cell(desc)} |")
        blocks.append("\n".join(rows) + "\n")

    other = [n for n in sorted(top) if n not in seen]
    if other:
        rows = ["## Other Commands\n", "| Command | Description |", "|---------|-------------|"]
        for name in other:
            cmd = top[name]
            link = f"{name}/index.md" if _is_group(cmd) else f"{name}.md"
            desc = cmd.short_help or cmd.get_short_help_str() or ""
            rows.append(f"| [`{name}`]({link}) | {_cell(desc)} |")
        blocks.append("\n".join(rows) + "\n")

    # Editorial guides (env-var tip, plugin system, common workflows) live below the
    # command index so the navigation stays at the top of the page.
    blocks.append(_editorial_include([], is_group=False))

    return "\n".join(b for b in blocks if b).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# Generation driver
# --------------------------------------------------------------------------- #
def _generate_pages(outdir: str) -> Dict[str, str]:
    """Return {page_path: content} for all CLI pages."""
    ctx = click.Context(cli, info_name="copick")
    _index_tree(ctx)

    pages: Dict[str, str] = {}
    pages[os.path.join(outdir, "index.md")] = _render_index(ctx)

    def walk(grp: click.Group, path: List[str]) -> None:
        for name in grp.list_commands(ctx):
            cmd = grp.get_command(ctx, name)
            if cmd is None or cmd.hidden:
                continue
            full = path + [name]
            if _is_group(cmd):
                pages[os.path.join(outdir, *full, "index.md")] = _render_group(cmd, full, ctx)
                walk(cmd, full)
            else:
                pages[os.path.join(outdir, *full[:-1], f"{name}.md")] = _render_leaf(cmd, full, ctx)

    walk(cli, [])
    return pages


# --------------------------------------------------------------------------- #
# Processing-tools gallery
# --------------------------------------------------------------------------- #
# The Data-Processing command groups that make up copick's "processing tools".
GALLERY_GROUPS = [("convert", "Convert"), ("process", "Process"), ("logical", "Logical")]

# Curated, representative tools for the home/quickstart carousel teaser.
CAROUSEL_HIGHLIGHTS = [
    ("convert", "picks2seg"),
    ("convert", "seg2picks"),
    ("convert", "mesh2seg"),
    ("convert", "picks2mesh"),
    ("process", "skeletonize"),
    ("process", "downsample"),
    ("logical", "clippicks"),
    ("logical", "meshop"),
]

# Per-tool thumbnails are dropped in by maintainers at
# ``docs/assets/tools/<group>/<command>.<ext>`` (any of the extensions below).
# Until one exists, the shared placeholder is used; no code change is needed to
# swap a real render in — just add the file and regenerate.
_TOOL_IMAGE_EXTS = ("png", "webp", "jpg", "jpeg", "svg")
_PLACEHOLDER_IMAGE = "assets/tools/_placeholder.svg"


def _tool_image(group: str, command: str) -> str:
    """Page-relative thumbnail path for a tool, falling back to the placeholder."""
    for ext in _TOOL_IMAGE_EXTS:
        if os.path.exists(os.path.join("docs", "assets", "tools", group, f"{command}.{ext}")):
            return f"assets/tools/{group}/{command}.{ext}"
    return _PLACEHOLDER_IMAGE


def _group_blurb(ctx: click.Context, group: str) -> str:
    grp = cli.get_command(ctx, group)
    if grp is None:
        return ""
    doc = inspect.getdoc(grp.callback) if grp.callback else None
    if doc:
        return doc.strip().split("\n\n")[0].replace("\n", " ")
    return grp.short_help or ""


def _group_tools(ctx: click.Context, group: str) -> List[Tuple[str, str]]:
    """Sorted (command_name, synopsis) for the leaf tools of a CLI group."""
    grp = cli.get_command(ctx, group)
    if grp is None:
        return []
    out = []
    for name in grp.list_commands(ctx):
        cmd = grp.get_command(ctx, name)
        if cmd is None or cmd.hidden:
            continue
        out.append((name, cmd.short_help or cmd.get_short_help_str() or ""))
    return out


def _tool_card(group: str, name: str, synopsis: str) -> str:
    img = _tool_image(group, name)
    link = f"cli/{group}/{name}.md"
    return (
        f"-   [![{name}]({img}){{ .tool-thumb }}]({link})\n\n"
        f"    **{name}**\n\n"
        f"    {synopsis}\n\n"
        f"    [:octicons-arrow-right-24: Details]({link})"
    )


def _render_gallery() -> str:
    ctx = click.Context(cli, info_name="copick")
    blocks = [
        AUTOGEN_HEADER,
        "# Processing Tools\n",
        "*Transform cryoET data from the command line — convert between picks, segmentations, "
        "and meshes; process volumes and segmentations; and run spatial / boolean operations. "
        "Every tool below is a `copick` CLI command; click through for full usage and examples.*\n",
    ]
    if os.path.exists("docs/cli_editorial/processing_tools.md"):
        blocks.append('--8<-- "docs/cli_editorial/processing_tools.md"\n')

    for group, title in GALLERY_GROUPS:
        tools = _group_tools(ctx, group)
        if not tools:
            continue
        blocks.append(f"## {title}\n")
        blurb = _group_blurb(ctx, group)
        if blurb:
            blocks.append(f"{blurb}\n")
        cards = "\n\n".join(_tool_card(group, name, syn) for name, syn in tools)
        blocks.append('<div class="grid cards" markdown>\n\n' + cards + "\n\n</div>\n")

    return "\n".join(b for b in blocks if b).rstrip() + "\n"


# Seconds the marquee takes to traverse one card; the full loop duration scales
# with card count so every carousel auto-scrolls at the same gentle speed.
_MARQUEE_SECONDS_PER_CARD = 6


def _marquee(cards: List[str]) -> str:
    """Wrap card markdown into an infinite, auto-scrolling marquee.

    Two identical card groups sit in a flex track; translating the track by one
    group width loops seamlessly. The second group is ``aria-hidden`` (a visual
    duplicate). Loop duration scales with the card count for a constant speed.
    The CSS (``.tool-marquee*`` in extra.css) pauses on hover/focus and falls back
    to a manual scroll strip under ``prefers-reduced-motion``.
    """
    group = "\n\n".join(cards)
    duration = max(20, len(cards) * _MARQUEE_SECONDS_PER_CARD)
    return (
        '<div class="tool-marquee" markdown>\n'
        f'<div class="tool-marquee__track" markdown style="--marquee-duration: {duration}s">\n\n'
        f'<div class="tool-marquee__group" markdown>\n\n{group}\n\n</div>\n\n'
        f'<div class="tool-marquee__group" markdown aria-hidden="true">\n\n{group}\n\n</div>\n\n'
        "</div>\n</div>"
    )


def _render_carousel() -> str:
    ctx = click.Context(cli, info_name="copick")
    items = []
    for group, name in CAROUSEL_HIGHLIGHTS:
        grp = cli.get_command(ctx, group)
        cmd = grp.get_command(ctx, name) if grp is not None else None
        if cmd is None or cmd.hidden:
            continue
        synopsis = cmd.short_help or cmd.get_short_help_str() or ""
        img = _tool_image(group, name)
        link = f"cli/{group}/{name}.md"
        items.append(
            f"-   [![{name}]({img}){{ .tool-thumb }}]({link})\n\n    **[{name}]({link})**\n\n    {synopsis}",
        )
    return (
        "<!-- AUTOGENERATED by `make_cli_docs`. Do not edit by hand. -->\n\n"
        + _marquee(items)
        + "\n\n[:octicons-arrow-right-24: Browse all processing tools](processing_tools.md)\n"
    )


# Ecosystem viewers featured in the home/Ecosystem-Tools showcase. The rich
# per-tool content lives in docs/tools.md; this is just the visual teaser strip.
# Each entry: (display name, tools.md anchor, preferred image path, one-liner).
# Drop a real screenshot at the preferred path to replace the placeholder.
ECOSYSTEM_VIEWERS = [
    (
        "ChimeraX-copick",
        "chimerax-copick",
        "assets/chimerax-copick.png",
        "Visualize and curate copick datasets in UCSF ChimeraX.",
    ),
    (
        "napari-copick",
        "napari-copick",
        "assets/tools/ecosystem/napari-copick.png",
        "Browse and curate copick datasets in napari.",
    ),
    (
        "CellCanvas",
        "cellcanvas",
        "assets/tools/ecosystem/cellcanvas.png",
        "Interactive 3D segmentation in napari, backed by copick.",
    ),
    (
        "copick-live",
        "copick-live",
        "assets/tools/ecosystem/copick-live.png",
        "Track collaborative picking and curation in a web dashboard.",
    ),
]


def _resolve_image(page_rel_path: str) -> str:
    """Return ``page_rel_path`` if the file exists under docs/, else the placeholder."""
    return page_rel_path if os.path.exists(os.path.join("docs", page_rel_path)) else _PLACEHOLDER_IMAGE


def _render_ecosystem_carousel() -> str:
    items = []
    for name, anchor, image, blurb in ECOSYSTEM_VIEWERS:
        img = _resolve_image(image)
        link = f"tools.md#{anchor}"
        items.append(
            f"-   [![{name}]({img}){{ .tool-thumb }}]({link})\n\n    **[{name}]({link})**\n\n    {blurb}",
        )
    return (
        "<!-- AUTOGENERATED by `make_cli_docs`. Do not edit by hand. -->\n\n"
        + _marquee(items)
        + "\n\n[:octicons-arrow-right-24: Explore the copick ecosystem](tools.md)\n"
    )


def _generate_gallery() -> Dict[str, str]:
    """Return {path: content} for the generated gallery page and carousel teasers."""
    return {
        "docs/processing_tools.md": _render_gallery(),
        "docs/snippets/processing_carousel.snippet": _render_carousel(),
        "docs/snippets/ecosystem_carousel.snippet": _render_ecosystem_carousel(),
    }


# --------------------------------------------------------------------------- #
# Nav rewrite (zensical.toml)
# --------------------------------------------------------------------------- #
def _nav_subtree() -> list:
    """Build the CLI-Reference nav subtree as plain dict/list, grouped by category."""
    ctx = click.Context(cli, info_name="copick")
    top = {name: cli.get_command(ctx, name) for name in cli.list_commands(ctx)}
    top = {k: v for k, v in top.items() if v is not None and not v.hidden}

    def entry(name: str, cmd: click.Command, path: List[str]) -> dict:
        full = path + [name]
        if _is_group(cmd):
            children: list = [{"Overview": "cli/" + "/".join(full) + "/index.md"}]
            for sub in cmd.list_commands(ctx):
                subcmd = cmd.get_command(ctx, sub)
                if subcmd is None or subcmd.hidden:
                    continue
                children.append(entry(sub, subcmd, full))
            return {name: children}
        return {name: "cli/" + "/".join(full) + ".md"}

    nav: list = [{"Overview": "cli/index.md"}]
    seen = set()
    for category, names in COMMAND_CATEGORIES.items():
        present = [n for n in sorted(names) if n in top]
        if not present:
            continue
        seen.update(present)
        nav.append({category: [entry(n, top[n], []) for n in present]})
    other = [n for n in sorted(top) if n not in seen]
    if other:
        nav.append({"Other Commands": [entry(n, top[n], []) for n in other]})
    return nav


def _fmt_nav_element(key: str, value, indent: int) -> str:
    """Serialise one nav element as a TOML inline table, matching the file's style.

    Produces the same progressively-indented, fully-quoted-key style as the
    hand-written nav entries (4 spaces per level).
    """
    pad = "    " * indent
    if isinstance(value, list):
        lines = [f'{pad}{{"{key}" = [']
        for el in value:
            ((child_key, child_val),) = el.items()
            lines.append(_fmt_nav_element(child_key, child_val, indent + 1) + ",")
        lines.append(f"{pad}]}}")
        return "\n".join(lines)
    return f'{pad}{{"{key}" = "{value}"}}'


def _find_cli_ref_span(text: str) -> Optional[Tuple[int, int]]:
    """Return (start, end) char offsets of the ``{"CLI Reference" = ...}`` nav element.

    Brace-balanced scan; paths/titles in the nav contain no braces so this is
    unambiguous. Works whether the element is the original ``"cli.md"`` string or
    a previously-generated nested block (idempotent).
    """
    match = re.search(r'\{\s*"CLI Reference"\s*=', text)
    if not match:
        return None
    start = match.start()
    depth = 0
    in_str = False
    for i in range(start, len(text)):
        ch = text[i]
        if ch == '"' and text[i - 1] != "\\":
            in_str = not in_str
        elif not in_str:
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    return start, i + 1
    return None


def _rewrite_nav(config_path: str, write: bool) -> Tuple[bool, str]:
    """Rewrite only the ``CLI Reference`` element of the nav array. Returns (changed, new_text)."""
    with open(config_path) as fh:
        original = fh.read()

    span = _find_cli_ref_span(original)
    if span is None:
        logger.warning("No 'CLI Reference' nav element in %s; skipping nav rewrite.", config_path)
        return False, original

    element = _fmt_nav_element("CLI Reference", _nav_subtree(), indent=1).lstrip()
    start, end = span
    new_text = original[:start] + element + original[end:]

    # Safety net: never write a config we cannot parse.
    try:
        import tomllib

        tomllib.loads(new_text)
    except ImportError:
        pass

    changed = new_text != original
    if changed and write:
        with open(config_path, "w") as fh:
            fh.write(new_text)
    return changed, new_text


# --------------------------------------------------------------------------- #
# Filesystem application
# --------------------------------------------------------------------------- #
def _write_if_changed(path: str, content: str) -> bool:
    if os.path.exists(path):
        with open(path) as fh:
            if fh.read() == content:
                return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(content)
    return True


def _prune_stale(outdir: str, valid: set) -> List[str]:
    """Remove autogenerated pages under ``outdir`` that no longer correspond to a command."""
    removed = []
    for root, _dirs, files in os.walk(outdir):
        for fname in files:
            if not fname.endswith(".md"):
                continue
            full = os.path.join(root, fname)
            if full in valid:
                continue
            with open(full) as fh:
                head = fh.read(120)
            if head.startswith("<!-- AUTOGENERATED"):
                os.remove(full)
                removed.append(full)
    return removed


@click.command(context_settings={"show_default": True})
@click.option(
    "--outdir",
    type=click.Path(file_okay=False),
    default="docs/cli",
    help="Output directory for generated CLI pages.",
)
@click.option(
    "--config",
    "config_path",
    type=click.Path(dir_okay=False),
    default="zensical.toml",
    help="Zensical config whose CLI-Reference nav node is rewritten.",
)
@click.option(
    "--check",
    is_flag=True,
    default=False,
    help="Verify pages/nav are up to date; exit non-zero on drift (no writes).",
)
@click.option("--prune/--no-prune", default=True, help="Remove stale autogenerated pages with no matching command.")
def main(outdir: str, config_path: str, check: bool, prune: bool) -> None:
    """Generate the per-command CLI reference from the assembled copick CLI."""
    pages = {**_generate_pages(outdir), **_generate_gallery()}

    if check:
        drift: List[str] = []
        for path, content in pages.items():
            if not os.path.exists(path):
                drift.append(f"missing: {path}")
            else:
                with open(path) as fh:
                    if fh.read() != content:
                        drift.append(f"changed: {path}")
        nav_changed, _ = _rewrite_nav(config_path, write=False)
        if nav_changed:
            drift.append(f"changed: {config_path} (nav)")
        if drift:
            logger.error("CLI docs are out of date. Run `make_cli_docs`.")
            for item in drift[:50]:
                logger.error("  %s", item)
            raise SystemExit(1)
        logger.info("CLI docs are up to date (%d pages).", len(pages))
        return

    written = sum(_write_if_changed(path, content) for path, content in pages.items())
    removed = _prune_stale(outdir, set(pages)) if prune else []
    nav_changed, _ = _rewrite_nav(config_path, write=True)

    logger.info(
        "Generated %d pages (%d updated), incl. the processing-tools gallery, pruned %d stale, nav %s.",
        len(pages),
        written,
        len(removed),
        "rewritten" if nav_changed else "unchanged",
    )


if __name__ == "__main__":
    main()
